name: "Terraform-infra"

on:
  push:
    branches:
      - feature
      - main
  workflow_dispatch:
  
jobs:
  terraform:
    name: "Terraform"
    runs-on: Ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGION: 'us-east-1'
    
    steps:
     - name: Checkout Code
       uses: actions/checkout@v4

     - name: Terraform setup
       uses: hashicorp/setup-terraform@v1

     - name: Terraform init
       id: init
       run: terraform init

     - name: Terraform plan
       id: plan
       if: github.event_name == 'push'
       run: terraform plan -no-color

     - name: Terraform plan status
       if: steps.plan.outcome == 'failure'
       run: exit 1

     - name: Terraform apply
       id: apply
       if: github.ref == 'refs/heads/main' && github.event_name == 'push'
       run: terraform apply -auto-approve